#include "even_fibonacci_numbers.h"

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

void even_fibonacci_numbers() {
	int n1 = 1, n2 = 2;
	int result_fib = 0, sum_even = 2;
	while (result_fib < 4000000) {
		result_fib = n1 + n2;
		n1 = n2;
		n2 = result_fib;
		if (result_fib % 2 == 0) {
			sum_even += result_fib;
		}
	}
	cout << sum_even;
}

